spring.application.name=Job-Portal

spring.data.mongodb.auto-index-creation=true
spring.data.mongodb.database=mongodb://localhost:27017/jobPortal

#EMAIL-PROPERTIES

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=dummygmail1212@gmail.com
spring.mail.password=xpwn kwgb gkox kiha
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true


#user.name.absent = Name is null or blank.
#user.email.absent = Email is null or blank.
#user.email.invalid = Email is invalid.
#user.password.absent = Password is null or blank.
#user.password.invalid = uppercase, lowercase,number,special character and 8-15.


USER_FOUND = User have already register.
USER_NOT-FOUND = User is not register.
INVALID_CREDENTIALS = Invalid_Credentials.
OTP_INCORRECT=OTP is invalid.
OTP_NOT_FOUND=OTP is expired.



